apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend
      containers:
      - image: guiwessel/backend:latest
        name: backend
        ports:
        - containerPort: 8706
          name: backend
        env:
          - name: PORT
            value: "8706"
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DATABASE_URI
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: REDIS_HOST
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: REDIS_PASSWORD