apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-listener-ports: "80"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    alb.ingress.kubernetes.io/target-type: "ip"
spec:
  type: LoadBalancer
  ports:
  - name: "frontend-service"
    port: 443
    targetPort: 3000
  selector:
    app: frontend
    